In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#CreatethePosition_Salariesdataset
Data={'Position':['CEO','charman','director','SeniorManager','JuniorManager','Intern'],
'Level':[1,2,3,4,5,6],
'Salary':[50000,80000,110000,150000,200000,250000]}
df=pd.DataFrame(Data)
#Identifytheindependentandtargetvariables
X=df.iloc[:,1:2].values
Y=df.iloc[:,2].values
#Splitthevariablesintotrainingandtestingsetswitha7:3ratio
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
#Printthetrainingandtestingsets
print("X_train:\n",X_train)
print("y_train:\n",y_train)
print("X_test:\n",X_test)
print("y_test:\n",y_test)
#Buildasimplelinearregressionmodel
Regressor=LinearRegression()
Regressor.fit(X_train,y_train)
#Printthecoefficientsandintercept
print("Coefficients:",Regressor.coef_)
print("Intercept : ",Regressor.intercept_)

X_train:
 [[2]
 [4]
 [1]
 [5]]
y_train:
 [ 80000 150000  50000 200000]
X_test:
 [[6]
 [3]]
y_test:
 [250000 110000]
Coefficients: [37000.]
Intercept :  9000.00000000003


In [7]:
#slip.2.LR model
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
#Create the Position_Salaries dataset

Data={'YearsExperience':[1,2,3,4,5,6,7,8,9,10],
'Salary':[50000,60000,70000,80000,90000,100000,110000,120000,130000,140000]}
df=pd.DataFrame(Data)

#Identify the independent and targetvariables
X=df.iloc[:,0:1].values
Y=df.iloc[:,1].values
#Split the variables into training and testing sets with 7:3 ratio
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)
#Print the training and testing sets
print("X_train:\n",X_train)
print("y_train:\n",y_train)
print("X_test:\n",X_test)
print("y_test:\n",y_test)
#Build asimple linear regression model
Regressor=LinearRegression()
Regressor.fit(X_train,y_train)
#Print the coefficient s and intercept
print("Coefficients:",Regressor.coef_)
print("Intercept : ",Regressor.intercept_)

X_train:
 [[10]
 [ 2]
 [ 7]
 [ 8]
 [ 4]
 [ 1]
 [ 6]]
y_train:
 [140000  60000 110000 120000  80000  50000 100000]
X_test:
 [[3]
 [9]
 [5]]
y_test:
 [ 70000 130000  90000]
Coefficients: [10000.]
Intercept :  39999.999999999985


In [9]:
#slip 3. logistic regression
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# Dataset
data = {
    'UserID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Gender': ['Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Female'],
    'Age': [19, 35, 26, 27, 19, 27, 32, 25, 33, 45],
    'EstimatedSalary': [19000, 20000, 43000, 57000, 76000, 58000, 82000, 32000, 69000, 65000],
    'Purchased': [0, 0, 0, 1, 1, 0, 1, 0, 1, 1]
}     # Create DataFrame
df = pd.DataFrame(data)
# Encode Gender as numeric (Male:1, Female:0)
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})
# Features and target
X = df.iloc[:, 1:4].values  # Gender, Age, EstimatedSalary
y = df.iloc[:, 4].values    # Purchased
# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
# Train Logistic Regression model
lr = LogisticRegression(random_state=0)
lr.fit(X_train, y_train)
# Predict a single observation
observation = [[0, 30, 87000]]
prediction = lr.predict(observation)
print("Single prediction:", prediction)
# Predict multiple observations
observations = [[0, 30, 87000], [1, 50, 45000], [1, 22, 30000]]
predictions = lr.predict(observations)
print("Multiple predictions:", predictions)


Single prediction: [1]
Multiple predictions: [1 1 0]


In [28]:
#slip 4 .Linear Regression
import random
import pandas as pd
from sklearn.linear_model import LinearRegression

# Create the dataset
fish_species = ['Tuna', 'Salmon', 'Trout', 'Bass', 'Sardine', 'Cod', 'Mackerel']
weights = []

for i in range(50):
    fish_weight = []
    for j in range(7):
        weight = random.randint(1, 20)
        fish_weight.append(weight)
    weights.append(fish_weight)

# Create DataFrame
df = pd.DataFrame(weights, columns=fish_species)
# Create the linear regression model
X = df.iloc[:, :-1]  # independent variables (Tuna to Cod)
y = df.iloc[:, -1]   # target variable (Mackerel)
model = LinearRegression()
model.fit(X, y)
# Define a new fish's measurements (Tuna to Cod)
new_fish = [[10, 12, 15, 7, 4, 8]]  # Example input
# Convert to DataFrame
new_fish_df = pd.DataFrame(new_fish, columns=fish_species[:-1])
# Predict the weight of Mackerel
predicted_weight = model.predict(new_fish_df)
print("Predicted weight of Mackerel:", predicted_weight[0])



Predicted weight of Mackerel: 8.416928615802018


In [29]:
#slip 5 logistic regression
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the iris dataset
iris = load_iris()

# Create a DataFrame from the dataset
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

# View basic statistical details of the different species
print("Statistical details of Iris-setosa:")
print(df[df['target'] == 0].describe())

print("\nStatistical details of Iris-versicolor:")
print(df[df['target'] == 1].describe())

print("\nStatistical details of Iris-virginica:")
print(df[df['target'] == 2].describe())

# Split the data into training and testing sets
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y,
                    test_size=0.2, random_state=42)

# Fit a logistic regression model
logreg = LogisticRegression(max_iter=200)
# Added max_iter to ensure convergence
logreg.fit(X_train, y_train)

# Make predictions on the test set
y_pred = logreg.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy of the logistic regression model:", accuracy)


Statistical details of Iris-setosa:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           50.00000         50.000000          50.000000   
mean             5.00600          3.428000           1.462000   
std              0.35249          0.379064           0.173664   
min              4.30000          2.300000           1.000000   
25%              4.80000          3.200000           1.400000   
50%              5.00000          3.400000           1.500000   
75%              5.20000          3.675000           1.575000   
max              5.80000          4.400000           1.900000   

       petal width (cm)  target  
count         50.000000    50.0  
mean           0.246000     0.0  
std            0.105386     0.0  
min            0.100000     0.0  
25%            0.200000     0.0  
50%            0.200000     0.0  
75%            0.300000     0.0  
max            0.600000     0.0  

Statistical details of Iris-versicolor:
       sepal length (cm)  sepal

In [6]:
#slip 6.APRIORI ALGORITHM 
pip install mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Create the dataset
TID = {
    1: ["bread", "milk"],
    2: ["bread", "diaper", "beer", "eggs"],
    3: ["milk", "diaper", "beer", "coke"],
    4: ["bread", "milk", "diaper", "beer"],
    5: ["bread", "milk", "diaper", "coke"]
}

# Prepare transactions list
transactions = []
for key, value in TID.items():
    transactions.append(value)

# Convert the categorical values into numeric format
te = TransactionEncoder()
te_ary = te.fit_transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

# Apply the Apriori algorithm with different min_support values
min_sup_values = [0.2, 0.4, 0.6]

for min_sup in min_sup_values:
    print(f"\nMin_sup: {min_sup}")
    
    frequent_itemsets = apriori(df, min_support=min_sup, use_colnames=True)
    print("Frequent Itemsets:")
    print(frequent_itemsets)
    
    rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
    print("Association Rules:")
    print(rules)


SyntaxError: invalid syntax (1818111159.py, line 2)

In [5]:
#slip 7

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Read the dataset
df_raw = pd.read_csv('Market_Basket_Optimisation.csv', header=None)
# Convert the dataset into a list of transactions
transactions = []
for i in range(len(df_raw)):
    transaction = [str(item) for item in df_raw.iloc[i] if pd.notna(item)]
    transactions.append(transaction)
# Apply one-hot encoding
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

# Generate frequent itemsets using the Apriori algorithm
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)

# Generate association rules from frequent itemsets
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
# Display information
print("Original Dataset (first 5 transactions as one-hot encoded):\n")
print(df.head())
print("\nFrequent Itemsets:\n")
print(frequent_itemsets)
print("\nAssociation Rules:\n")
print(rules)


ModuleNotFoundError: No module named 'mlxtend'

In [21]:
#slip 9, own transaction dataset
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Define items and transactions
items = ['item1', 'item2', 'item3', 'item4']
transactions = [
    ['item1', 'item2', 'item3'],
    ['item2', 'item3'],
    ['item1', 'item2', 'item4'],
    ['item1', 'item4'],
    ['item2', 'item3', 'item4'],
    ['item1', 'item3', 'item4'],
    ['item1', 'item2'],
    ['item1', 'item3'],
    ['item3', 'item4'],
    ['item2', 'item4']
]

# Convert the transactions into a binary matrix
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)

# Convert the binary matrix into a pandas DataFrame
df = pd.DataFrame(te_ary, columns=te.columns_)

# Generate frequent itemsets with a minimum support of 0.3
frequent_itemsets = apriori(df, min_support=0.3, use_colnames=True)

# Generate association rules with a minimum confidence of 0.7
association_rules_df = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

# Print the frequent itemsets and association rules
print("Frequent Itemsets:")
print(frequent_itemsets)

print("\nAssociation Rules:")
print(association_rules_df)


Frequent Itemsets:
   support        itemsets
0      0.6         (item1)
1      0.6         (item2)
2      0.6         (item3)
3      0.6         (item4)
4      0.3  (item2, item1)
5      0.3  (item3, item1)
6      0.3  (item4, item1)
7      0.3  (item3, item2)
8      0.3  (item4, item2)
9      0.3  (item4, item3)

Association Rules:
Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []


In [22]:
#slip 10,APRIORI
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Create the dataset
dataset = {
    1: ["eggs", "milk", "bread"],
    2: ["eggs", "apple"],
    3: ["milk", "bread"],
    4: ["apple", "milk"],
    5: ["milk", "apple", "bread"]
}

# Convert categorical values into numeric format
te = TransactionEncoder()
te_ary = te.fit(dataset.values()).transform(dataset.values())
df = pd.DataFrame(te_ary, columns=te.columns_)

# Apply Apriori algorithm
min_sup = 0.4
frequent_itemsets = apriori(df, min_support=min_sup, use_colnames=True)

# Generate association rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

# Print results
print("Frequent Itemsets:\n", frequent_itemsets)
print("\nAssociation Rules:\n", rules)


Frequent Itemsets:
    support       itemsets
0      0.6        (apple)
1      0.6        (bread)
2      0.4         (eggs)
3      0.8         (milk)
4      0.4  (milk, apple)
5      0.6  (bread, milk)

Association Rules:
   antecedents consequents  antecedent support  consequent support  support  \
0     (apple)      (milk)                 0.6                 0.8      0.4   
1     (bread)      (milk)                 0.6                 0.8      0.6   
2      (milk)     (bread)                 0.8                 0.6      0.6   

   confidence      lift  representativity  leverage  conviction  \
0    0.666667  0.833333               1.0     -0.08         0.6   
1    1.000000  1.250000               1.0      0.12         inf   
2    0.750000  1.250000               1.0      0.12         1.6   

   zhangs_metric  jaccard  certainty  kulczynski  
0      -0.333333     0.40  -0.666667    0.583333  
1       0.500000     0.75   1.000000    0.875000  
2       1.000000     0.75   0.375000    0.

In [32]:
#slip 11.
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

transactions = [
    ['eggs', 'milk', 'bread'],
    ['eggs', 'apple'],
    ['milk', 'bread'],
    ['apple', 'milk'],
    ['milk', 'apple', 'bread']
]

# Convert to one-hot encoded DataFrame with boolean values
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_array, columns=te.columns_).astype(bool)  # ✅ fix here

# Generate frequent itemsets
freq_items = apriori(df, min_support=0.5, use_colnames=True)
print("Frequent Itemsets:\n", freq_items)

# Generate and sort association rules
rules = association_rules(freq_items, metric='support', min_threshold=0.05)
rules = rules.sort_values(['support', 'confidence'], ascending=[False, False])
print("\nAssociation Rules:\n", rules)


Frequent Itemsets:
    support       itemsets
0      0.6        (apple)
1      0.6        (bread)
2      0.8         (milk)
3      0.6  (bread, milk)

Association Rules:
   antecedents consequents  antecedent support  consequent support  support  \
0     (bread)      (milk)                 0.6                 0.8      0.6   
1      (milk)     (bread)                 0.8                 0.6      0.6   

   confidence  lift  representativity  leverage  conviction  zhangs_metric  \
0        1.00  1.25               1.0      0.12         inf            0.5   
1        0.75  1.25               1.0      0.12         1.6            1.0   

   jaccard  certainty  kulczynski  
0     0.75      1.000       0.875  
1     0.75      0.375       0.875  


In [41]:
#slip 12
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Create a random dataset with 10 samples
heights = np.random.normal(170, 10, 10)
weights = np.random.normal(70, 5, 10)

# Combine the two arrays into a single dataset
dataset = pd.DataFrame({'Height': heights, 'Weight': weights})

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(dataset['Height'],
                        dataset['Weight'], test_size=0.2, random_state=42)

# Create a Linear Regression model and fit it to the training data
lr_model = LinearRegression()
lr_model.fit(X_train.values.reshape(-1, 1), y_train)

# Print the model coefficients
print('Model Coefficients:', lr_model.coef_)

# Predict the weights for the test data and print the predictions
y_pred = lr_model.predict(X_test.values.reshape(-1, 1))
print('Predictions:', y_pred)


Model Coefficients: [-0.27541473]
Predictions: [65.16840092 75.09427813]


In [7]:
#slip 13
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/nursery/nursery.data'
names = ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'class']
dataset = pd.read_csv(url, names=names)

# Prepare data
X = pd.get_dummies(dataset.drop('class', axis=1))
y = dataset['class']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.9972993827160493

Classification Report:
               precision    recall  f1-score   support

   not_recom       1.00      1.00      1.00       870
    priority       1.00      1.00      1.00       873
   recommend       0.00      0.00      0.00         2
  spec_prior       1.00      1.00      1.00       785
  very_recom       0.94      1.00      0.97        62

    accuracy                           1.00      2592
   macro avg       0.79      0.80      0.79      2592
weighted avg       1.00      1.00      1.00      2592



c:\Users\punam\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\punam\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\punam\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [46]:
#slip 8                                                     import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
# Load the dataset
df = pd.read_csv('market_basket.csv', header=None)
# Convert the dataset into a list of transactions
transactions = []
for i in range(len(df)):
    transaction = [str(item) for item in df.iloc[i] if pd.notna(item)]
    transactions.append(transaction)
# Convert categorical values to numeric format
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

# Generate frequent itemsets
frequent_itemsets = apriori(df_encoded, min_support=0.01, use_colnames=True)
# Generate association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
# Display dataset information
print("Dataset information:")
print(df_encoded.info())

# Display the frequent itemsets
print("\nFrequent itemsets:")
print(frequent_itemsets)
# Display the association rules
print("\nAssociation rules:")
print(rules)

FileNotFoundError: [Errno 2] No such file or directory: 'market_basket.csv'

In [8]:
#slip 14
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
import pandas as pd

# Create the dataset
TID = {
    1: ['apple', 'mango', 'banana'],
    2: ['mango', 'banana', 'cabbage', 'carrots'],
    3: ['mango', 'banana', 'carrots'],
    4: ['mango', 'carrots']
}

# Convert the categorical values into numeric format
te = TransactionEncoder()
te_ary = te.fit([TID[i] for i in TID]).transform([TID[i] for i in TID])
df = pd.DataFrame(te_ary, columns=te.columns_)

# Apply the apriori algorithm with different min_sup values
min_sup_values = [0.25, 0.5, 0.75]

for min_sup in min_sup_values:
    frequent_itemsets = apriori(df, min_support=min_sup, use_colnames=True)
    print("Frequent itemsets with min_sup =", min_sup)
    print(frequent_itemsets)
    print("\n")


ModuleNotFoundError: No module named 'mlxtend'

In [9]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
# Create the dataset
data = {
    'No': [1, 2, 3, 4],
    'Company': ['Tata', 'MG', 'Kia', 'Hyundai'],
    'Model': ['Nexon', 'Astor', 'Seltos', 'Creta'],
    'Year': [2017, 2021, 2019, 2015]
}
df = pd.DataFrame(data)
# Prepare transaction-like format (drop 'No' column)
transactions = df.drop(columns='No').astype(str).values.tolist()

# Convert to one-hot encoded format
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

# Apply Apriori with lower min_support
frequent_itemsets = apriori(df_encoded, min_support=0.25, use_colnames=True)

# Generate rules only if itemsets are found
if not frequent_itemsets.empty:
    rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
    print("Frequent Itemsets:\n", frequent_itemsets)
    print("\nAssociation Rules:\n", rules)
else:
    print("No frequent itemsets found.")



ModuleNotFoundError: No module named 'mlxtend'